export const FETCH_SESSION_REQUEST = 'FETCH_SESSION_REQUEST'
export const FETCH_SESSION_SUCCESS = 'FETCH_SESSION_SUCCESS'
export const FETCH_SESSION_FAILURE = 'FETCH_SESSION_FAILURE'

export const REMOVE_SESSION_REQUEST = 'REMOVE_SESSION_REQUEST'
export const REMOVE_SESSION_SUCCESS = 'REMOVE_SESSION_SUCCESS'
export const REMOVE_SESSION_FAILURE = 'REMOVE_SESSION_FAILURE'

