export const FETCH_TEAM_REQUEST = 'FETCH_TEAM_REQUEST'
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS'
export const FETCH_TEAM_FAILURE = 'FETCH_TEAM_FAILURE'

export const ADD_TEAM_REQUEST = 'ADD_TEAM_REQUEST'
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS'
export const ADD_TEAM_FAILURE = 'ADD_TEAM_FAILURE'

export const MODIFY_TEAM_REQUEST = 'UPDATE_TEAM_REQUEST'
export const MODIFY_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS'
export const MODIFY_TEAM_FAILURE = 'UPDATE_TEAM_FAILURE'

export const REMOVE_TEAM_REQUEST = 'REMOVE_TEAM_REQUEST'
export const REMOVE_TEAM_SUCCESS = 'REMOVE_TEAM_SUCCESS'
export const REMOVE_TEAM_FAILURE = 'REMOVE_TEAM_FAILURE'

export const SET_CURRENT_TEAM = 'SET_CURRENT_TEAM'

export const FETCH_EMPLOYEE_REQUEST = 'FETCH_EMPLOYEE_REQUEST'
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS'
export const FETCH_EMPLOYEE_FAILURE = 'FETCH_EMPLOYEE_FAILURE'

export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST'
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS'
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE'

export const MODIFY_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST'
export const MODIFY_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const MODIFY_EMPLOYEE_FAILURE = 'UPDATE_EMPLOYEE_FAILURE'

export const REMOVE_EMPLOYEE_REQUEST = 'REMOVE_EMPLOYEE_REQUEST'
export const REMOVE_EMPLOYEE_SUCCESS = 'REMOVE_EMPLOYEE_SUCCESS'
export const REMOVE_EMPLOYEE_FAILURE = 'REMOVE_EMPLOYEE_FAILURE'

export const FETCH_KEYWORD_REQUEST = 'FETCH_KEYWORD_REQUEST'
export const FETCH_KEYWORD_SUCCESS = 'FETCH_KEYWORD_SUCCESS'
export const FETCH_KEYWORD_FAILURE = 'FETCH_KEYWORD_FAILURE'

export const ADD_KEYWORD_REQUEST = 'ADD_KEYWORD_REQUEST'
export const ADD_KEYWORD_SUCCESS = 'ADD_KEYWORD_SUCCESS'
export const ADD_KEYWORD_FAILURE = 'ADD_KEYWORD_FAILURE'

export const MODIFY_KEYWORD_REQUEST = 'UPDATE_KEYWORD_REQUEST'
export const MODIFY_KEYWORD_SUCCESS = 'UPDATE_KEYWORD_SUCCESS'
export const MODIFY_KEYWORD_FAILURE = 'UPDATE_KEYWORD_FAILURE'

export const REMOVE_KEYWORD_REQUEST = 'REMOVE_KEYWORD_REQUEST'
export const REMOVE_KEYWORD_SUCCESS = 'REMOVE_KEYWORD_SUCCESS'
export const REMOVE_KEYWORD_FAILURE = 'REMOVE_KEYWORD_FAILURE'