export const FETCH_DISEASE_REQUEST = 'FETCH_DISEASE_REQUEST';
export const FETCH_DISEASE_SUCCESS = 'FETCH_DISEASE_SUCCESS';
export const FETCH_DISEASE_FAILURE = 'FETCH_DISEASE_FAILURE';

export const ADD_DISEASE_REQUEST = 'ADD_DISEASE_REQUEST';
export const ADD_DISEASE_SUCCESS = 'ADD_DISEASE_SUCCESS';
export const ADD_DISEASE_FAILURE = 'ADD_DISEASE_FAILURE';

export const MODIFY_DISEASE_REQUEST = 'MODIFY_DISEASE_REQUEST';
export const MODIFY_DISEASE_SUCCESS = 'MODIFY_DISEASE_SUCCESS';
export const MODIFY_DISEASE_FAILURE = 'MODIFY_DISEASE_FAILURE';

export const REMOVE_DISEASE_REQUEST = 'REMOVE_DISEASE_REQUEST';
export const REMOVE_DISEASE_SUCCESS = 'REMOVE_DISEASE_SUCCESS';
export const REMOVE_DISEASE_FAILURE = 'REMOVE_DISEASE_FAILURE';
