export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';

export const ADD_ARTICLE_REQUEST = 'ADD_ARTICLE_REQUEST';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_FAILURE = 'ADD_ARTICLE_FAILURE';

export const MODIFY_ARTICLE_REQUEST = 'MODIFY_ARTICLE_REQUEST';
export const MODIFY_ARTICLE_SUCCESS = 'MODIFY_ARTICLE_SUCCESS';
export const MODIFY_ARTICLE_FAILURE = 'MODIFY_ARTICLE_FAILURE';

export const REMOVE_ARTICLE_REQUEST = 'REMOVE_ARTICLE_REQUEST';
export const REMOVE_ARTICLE_SUCCESS = 'REMOVE_ARTICLE_SUCCESS';
export const REMOVE_ARTICLE_FAILURE = 'REMOVE_ARTICLE_FAILURE';
